### ISSUE TITLE
Présentation du site VisitMorocco

### ISSUE THREAD

**Issue by Jad-Bel** [Jad-Bel/Brief-3-group-ACE#20]

**Comment by Jad-Bel** [comment]
Développement d'une plateforme interactive pour présenter les principales destinations marocaines, avec un design simple et accessible pour une navigation fluide et informative.

**Comment by amhine** [comment]
This is the presentation of the VisitMorocco project website: https://www.canva.com/design/DAGUkatx9HQ/r7JkCd0GXn9FRC_FaTgOVw/edit?utm_content=DAGUkatx9HQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
